### ISSUE TITLE
create waypoint list

### ISSUE THREAD

**Issue by fscbr** [ucatie/CarND-Capstone#1]
list of 200 points ahead published having correct target velocity

**Comment by fscbr** [comment]
list of 200 points ahead published having correct target velocity

**Comment by juampehidalgo** [comment]
Created dummy list of waypoints using parameter based velocity.
Node class does not store current vehicle state, nor waypoints at this state, as all calculations are done in /base_waypoints callback.
Implementation makes use of ROS TF library to transform between /world and /base_link (car's) reference frames, so that selecting waypoints ahead of the car is simply choosing waypoints with positive x coordinate.

**Comment by abes975** [comment]
probably current car pose has to be saved in a local variable as for now pose_cb does nothing..but we will probably need soon the car position in order to calculate the needed deceleration.

**Comment by SebastianNi** [comment]
The waypoint_updater is ready for use. We will see if it needs some fine tuning. So far it handles traffic_waypoints and publishes final_waypoints every time it receives base_waypoints. That means the fequency of final_waypoints can be adjusted by adjusting the frequency of base_waypoints.
